#!/bin/sh

# Определение директории, где находится xkeen.sh
script_dir="$(cd "$(dirname "$0")" && pwd)"

# Скрываем основную директорию xkeen
install_xkeen_rename() {
    script_dir="$script_dir"
    source_dir="_xkeen"
    target_dir=".xkeen"
    source_path="$script_dir/$source_dir"
    target_path="$script_dir/$target_dir"
    
    if [ -d "$source_path" ]; then
        if [ -d "$target_path" ]; then
            rm -rf "$target_path"
        fi
        mv "$source_path" "$target_path"
    fi
}

install_xkeen_rename

# Импортируем модули
. "$script_dir/.xkeen/import.sh"

# Очищаем журнал перед работой
	logs_clear

# Проверяем установку пакетов
	info_packages
	logs_packages_info_xkeen

# Собираем необходимую информацию о процессоре
	info_cpu
	logs_cpu_info_xkeen
	
# Проверяем установку xray
	info_xray
	logs_xray_info_xkeen

# Проверяем установленные базы geodata
	info_geodata
	logs_geodata_info_xkeen
	
# Проверяем установленные базы geoip
	info_geoip
	logs_geoip_info_xkeen

# Проверяем статусы автоматических обновлений
	info_cron
	logs_cron_info_xkeen

# Проверяем версию xkeen
	info_version_xkeen
	logs_version_xkeen_info_xkeen

# Проверяем актуальность xkeen
	info_compare_xkeen
	logs_compare_xkeen_info_xkeen
	
# Проверяем версию xray
	info_version_xray
	logs_version_xray_info_xkeen

# Проверяем актуальность xray
	info_compare_xray
	logs_compare_xray_info_xkeen

# Устанавливаем недостающие пакеты
	install_packages
	logs_install_packages_xkeen

	
while [ $# -gt 0 ]; do
    case "$1" in
	
        -i)	# Запуск полного цикла установки
			# Устанавливаем xray			
			eval "clear"
				if [ "$xray_installed" = "not_installed" ]; then
					download_xray
					logs_download_xray_info_xkeen
					
					install_xray
					
					xray_installed="installed"
				fi
				
			eval "clear" 
			# Обновляем xray	
				if [ "$info_compare_xray" = "update" ]; then
					download_xray
					logs_download_xray_info_xkeen
					
					install_xray
					
					xray_current_version="actual"
				fi
			eval "clear" 
			# Устанавливаем geoip
				choose_geoip
				logs_choose_geoip_info_xkeen
				
					delete_geoip
					logs_delete_geoip_info_xkeen
					
					install_geoip
					logs_install_geoip_info_xkeen

			eval "clear" 
			# Устанавливаем geodata
				choose_geodata
				logs_choose_geodata_info_xkeen
				
					delete_geodata
					logs_delete_geodata_info_xkeen
										
					install_geodata
					logs_install_geodata_info_xkeen
					
			eval "clear" 
			# Настраиваем автоматические обновления
				choose_update_cron
				logs_choose_update_cron_info_xkeen
				
			eval "clear" 
				choose_cron_time
				logs_choose_cron_time_info_xkeen
				
					delete_cron_task
					logs_delete_cron_task_info_xkeen
					
			#	choose_cron_time
					install_cron
					logs_install_cron_info_xkeen
					
			eval "clear" 
			# Устанавливаем configs xray
				install_configs
				logs_install_configs_info_xkeen
				
			# Удаляем предыдущие регистрации
				delete_register_xkeen
				logs_delete_register_xkeen_info_xkeen
				
				delete_register_xray
				
			# Регистрируем xray
				register_xray_list
				register_xray_control
				register_xray_status
				register_xray_initd

			# Регистрируем xkeen
				register_xkeen_list
				register_xkeen_control
				register_xkeen_status

			# Удаляем временные файлы
				delete_tmp
            shift
            ;;
			
        -ux)		#Запуск обновления xray
			if [ "$info_compare_xray" = "update" ]; then
				backup_xray
				download_xray
				install_xray
				
				delete_register_xray
				
				register_xray_list
				register_xray_control
				register_xray_status
				
				delete_tmp
				
			fi
            shift
            ;;
			
			
        -uk)		#Запуск обновления xkeen
			if [ "$info_compare_xkeen" = "update" ]; then
				backup_xkeen	
				download_xkeen
				install_xkeen
				
				delete_register_xkeen
				
				register_xkeen_list
				register_xkeen_control
				register_xkeen_status
				
				delete_tmp
			fi
            shift
            ;;
			
			
        -ugd)	#Запуск обновления баз geodata		
			if [ "$geo_exists_geodata_v2fly" = "installed" ]; then
				install_v2fly_geodata="true"
            fi
			
			if [ "$geo_exists_geodata_antifilter" = "installed" ]; then
                install_antifilter_geodata="true"
            fi
						
			if [ "$geo_exists_geodata_antizapret" = "installed" ]; then
				install_antizapret_geodata="true"
            fi
				
				install_geodata
            shift
            ;;
			
			
        -ugi)		#Запуск обновления баз geoip				
			if [ "$geo_exists_geoip_v2fly" = "installed" ]; then
				install_v2fly_geoip="true"
            fi
			
			if [ "$geo_exists_geoip_antifilter" = "installed" ]; then
                install_antifilter_geoip="true"
            fi
				
				install_geoip
            shift
            ;;
			
			
		-uac)	#Создать или изменить существующее правило автоматического обновления xkeen, xray, geoip, geodata	
				delete_cron_xkeen 2>/dev/null
				delete_cron_xray 2>/dev/null
				delete_cron_geoip 2>/dev/null
				delete_cron_geodata 2>/dev/null
				
                    chose_xkeen_cron_select=true
                    chose_xray_cron_select=true
                    chose_geodata_cron_select=true
                    chose_geoip_cron_select=true

				if input_concordance_list "Хотите установить единое время для всех обновлений?"; then
                        chose_all_cron_select=true
                        chose_xkeen_cron_select=false
                        chose_xray_cron_select=false
                        chose_geodata_cron_select=false
                        chose_geoip_cron_select=false
                    else
                        chose_all_cron_select=false
				fi
					
				choose_cron_time
				
				install_cron
            shift
            ;;
			
			
		-ukc)	#Создать или изменить существующее правило автоматического обновления xkeen
				delete_cron_xkeen
				
				chose_xkeen_cron_select=true
				choose_cron_time
				
				install_cron
            shift
            ;;
			
			
		-uxc)	#Создать или изменить существующее правило автоматического обновления xray
				delete_cron_xray
				
				chose_xray_cron_select=true
				choose_cron_time
				
				install_cron
            shift
            ;;
			
			
		-ugdc)	#Создать или изменить существующее правило автоматического обновления geodata
				delete_cron_geodata
				
				chose_geodata_cron_select=true
				choose_cron_time
				
				install_cron
            shift
            ;;
			
			
		-ugic)	#Создать или изменить существующее правило автоматического обновления geoip
				delete_cron_geoip
				
				chose_geoip_cron_select=true
				choose_cron_time
				
				install_cron
            shift
            ;;


		-rx)	#Зарегистрировать xray
				delete_register_xray
				register_xray_list
				register_xray_control
				register_xray_status
            shift
            ;;
			

		-ri)	#Создать правило автоматического запуска xkeen
				register_xray_initd
            shift
            ;;
			

		-rk)	#Зарегистрировать xkeen
				delete_register_xkeen
				register_xkeen_list
				register_xkeen_control
				register_xkeen_status
            shift
            ;;
			

			
		-dac)	#Удалить правила автоматического обновления xkeen, xray, geodata, geoip
				delete_cron_xkeen
				delete_cron_xray
				delete_cron_geodata
				delete_cron_geoip
            shift
            ;;
			
			
		-dkc)		#Удалить правило автоматического обновления xkeen
				delete_cron_xkeen
            shift
            ;;
			

		-dxc)		#Удалить правило автоматического обновления xray
				delete_cron_xray
            shift
            ;;
			

		-dgdc)		#Удалить правило автоматического обновления geodata
				delete_cron_geodata
            shift
            ;;
			
			
		-dgic)		#Удалить правило автоматического обновления geoip
				delete_cron_geoip
            shift
            ;;
			
			
		-dx)	#Удалить xray
				eval "opkg remove xray"
            shift
            ;;
			
			
		-dk)	#Удалить xkeen
				eval "opkg remove xkeen"
            shift
            ;;
			
			
		-dgd)	#Удалить базы geodata
				delete_geodata_key
            shift
            ;;
			
			
		-dgi)	#Удалить базы geoip
				delete_geoip_key
            shift
            ;;
			
			
		-dt)	#Удалить временные файлы xkeen
				delete_tmp
            shift
            ;;
			
			
		-dс)	#Удалить все конфиги xray
				delete_configs
            shift
            ;;
			
			
		-drx)	#Удалить регистрации xray
				delete_register_xray
            shift
            ;;
			

		-drk)	#Удалить регистрации xkeen
				delete_register_xkeen
            shift
            ;;


		-rrk)	#Обновить регистрацию xkeen
				delete_register_xkeen
				register_xkeen_list
				register_xkeen_control
				register_xkeen_status
				
            shift
            ;;
			
			
		-rrx)	#Обновить регистрацию xray
				delete_register_xray
				register_xray_list
				register_xray_control
				register_xray_status		
            shift
            ;;
				
			
		-rc)	#Переустановить конфиги xray
				install_configs
				
				delete_register_xray
				register_xray_list
				register_xray_control
				register_xray_status
            shift
            ;;
			
			
		-x)	#Переустановить xray
				eval "opkg remove xray" 
				download_xray
				install_xray
				xray_installed="installed"
				
				install_configs
				
				register_xray_list
				register_xray_control
				register_xray_status
				register_xray_initd
				
				if input_concordance_list "Хотите включить автоматическое обновление xray?"; then
                        chose_xray_cron_select=true
                    else
                        chose_xray_cron_select=false
				fi
				
				choose_cron_time
				install_cron
								
            shift
            ;;
			
			
		-k)	#Переустановить xkeen
				eval "opkg remove xkeen" 
				download_xkeen
				iinstall_xkeen
				
			
				register_xkeen_list
				register_xkeen_control
				register_xkeen_status
				
				if input_concordance_list "Хотите включить автоматическое обновление xkeen?"; then
                        chose_xkeen_cron_select=true
                    else
                        chose_xkeen_cron_select=false
				fi
				
				choose_cron_time
				install_cron
								
				delete_tmp
								
            shift
            ;;
			
		-xb)	#Сделать резервную копию xray
				backup_xray								
            shift
            ;;
						
		-kb)	#Резервное копирование xkeen
				backup_xkeen		
            shift
            ;;
			
		-cb)	#Сделать резервную конфигураций xray
				backup_configs						
            shift
            ;;
						
		-xbr)	# Восстановление резервной копировании xray
				restore_backup_xray								
            shift
            ;;
			
			
		-kbr)	# Восстановление резервной копировании xkeen
				restore_backup_xkeen		
            shift
            ;;
			
		-cbr)	# Восстановление резервной копировании конфигурационных файлов xray
				restore_backup_configs						
            shift
            ;;
			
						
		-connect)	# Тест соединения
				tests_connection
				
            shift
            ;;
			
		-portx)	# Показать прослушиваемые порты
				tests_ports_xray
			;;
			
		-ad)	# Можете купить Мне кофе
				author_donate					
            shift
            ;;
			
		-af)	# Обратная связь
				author_feedback			
            shift
            ;;
			
		-tests)	# Тестовый блок
				create_custom_dat_file
				
            shift
            ;;
			
			
		-arch)	# Подготавливает текущую сборку для релиза
				archive_xkeen
				
            shift
            ;;
			
		-h)	#Помощь			
				echo
				echo -e "     ${light_blue}xkeen${reset} — утилита для обеспечения работы xray на роутерах keenetic"
				echo 
				echo -e "     Пример использования ключей запуска: «xkeen ${green}-x${reset}», где ${green}-x${reset} — выбранный Вами ключ."
				echo "     Список доступных ключей запуска"
				echo
				echo -e "  ${yellow}Полный цикл установки${reset}"
				echo -e "     ${green}-i${reset} — Необходимые пакеты, xray и сервисы xkeen"
				echo 
				echo -e "  ${yellow}Обновление${reset}"
				echo -e "     ${green}-ux${reset} — xray"
				echo -e "     ${green}-uk${reset} — xkeen"
				echo -e "     ${green}-ugd${reset} — geodata"
				echo -e "     ${green}-ugi${reset} — geoip"
				echo 
				echo -e "  ${yellow}Включение или изменение правил обновления${reset}"
				echo -e "     ${green}-uac${reset} — xray, xkeen, geodata, geoip"
				echo -e "     ${green}-uxc${reset} — xray"
				echo -e "     ${green}-ukc${reset} — xkeen"
				echo -e "     ${green}-ugdc${reset} — geodata"
				echo -e "     ${green}-ugic ${reset}— geoip"
				echo 
				echo -e "  ${yellow}Регистрация${reset}"
				echo -e "     ${green}-rx${reset} — xray"
				echo -e "     ${green}-rk${reset} — xkeen"
				echo -e "     ${green}-ri${reset} — Автоматический запуск xray средствами init.d"
				echo 
				echo -e "  ${red}Удаление${reset}  /  Автоматические обновления"
				echo -e "     ${green}-dac${reset} — xray, xkeen, geodata, geoip"
				echo -e "     ${green}-dkc${reset} — xkeen"
				echo -e "     ${green}-dxc${reset} — xray"
				echo -e "     ${green}-dgdc${reset} — geodata"
				echo -e "     ${green}-dgic${reset} — geoip"
				echo
				echo -e "  ${red}Удаление${reset}  /  Утилиты и компоненты"
				echo -e "     ${green}-dx${reset} — xray"
				echo -e "     ${green}-dk${reset} — xkeen"
				echo -e "     ${green}-dgd${reset} — geodata"
				echo -e "     ${green}-dgi${reset} — geoip"
				echo -e "     ${green}-dс${reset} — Конфигурации xray"
				echo -e "     ${green}-dt${reset} — Временные файлы"
				echo
				echo -e "  ${red}Удаление${reset}  /  Регистрации"			
				echo -e "     ${green}-drx${reset} —  xray"
				echo -e "     ${green}-drk${reset} — xkeen"
				echo
				echo -e "  ${yellow}Обновление регистрации утилит${reset}"			
				echo -e "     ${green}-rrx${reset} —  xray"
				echo -e "     ${green}-rrk${reset} — xkeen"
				echo
				echo -e "  ${yellow}Переустановка${reset}"		
				echo -e "     ${green}-x${reset} — xray"
				echo -e "     ${green}-k${reset} — xkeen"
				echo -e "     ${green}-rc${reset} — Конфигурационные файлы xray"
				echo
				echo -e "  ${yellow}Резервные копии${reset} / Создание"
				echo -e "     ${green}-xb${reset} — xray"
				echo -e "     ${green}-kb${reset} — xkeen"
				echo -e "     ${green}-cb${reset} — Конфигурационные файлов xray"
				echo
				echo -e "  ${yellow}Резервные копии${reset} / Восстановление последней"
				echo -e "     ${green}-xbr${reset} — xray"
				echo -e "     ${green}-kbr${reset} — xkeen"
				echo -e "     ${green}-cbr${reset} — Конфигурационные файлы xray"
				echo
				echo -e "  ${yellow}Автор${reset}"
				echo -e "     ${green}-ad${reset} — Если Вам полезна утилита, можете купить Мне кофе"
				echo -e "     ${green}-af${reset} — Обратная связь"
				echo
            shift
            ;;
			
        *)
            echo -e "     Неизвестный ключ: ${red}$1${reset}"
            shift
            ;;
			
    esac
done